### ISSUE TITLE
Consider replacing error factories with real constructors

### ISSUE THREAD

**Issue by pluma** [jshttp/http-errors#11]
Currently the "constructors" are actually just factory functions and we have a total of three such factories in the code that do pretty much the same thing (`ClientError`, `ServerError` and the exported function).

The only reason `ServerError` and `ClientError` have any inheritance at all is that the `__proto__` property of the new error is manipulated directly. This is incompatible with some possible environments (the double underscores are there for a reason).

It would be nice if the two constructors were actual constructors (i.e. return `this`, not a retrofitted error). For an example of how this would work see [httperr@0.5.0](https://github.com/pluma/httperr/blob/0.5.0/index.js#L29-L32).

The obvious drawback is that `Object.prototype.toString` returns `[object Object]` instead of `[object Error]` and `util.isError` returns `false` (though instanceof checks pass as one would expect). The benefit is that this approach can be made to work in environments that don't support overriding `__proto__`.

**Comment by dougwilson** [comment]
Wow, this has been open for a long time :) So as you may have seen, I just closed it with a commit. The commit doesn't exactly correlate with the title of the issue, but I feel like it correlates a bit with the ideas floating around to the underlying issue, which was using `__proto__` in order to get a proper `[[Class]]` on the object.

The commit replaces using `__proto__` with the `setprototypeof` module, which simply uses the standardized `Object.setProtototypeOf` function, falls back to using `__proto__` if possible, otherwise will just copy the properties as a last resort. I think this should cover the compatibility bases.

**Comment by pluma** [comment]
Thanks @dougwilson. I appreciate the effort you're putting into these projects. I think the change is in spirit with this issue.

**Comment by dougwilson** [comment]
No problem :) I'm trying to match through here and pick up all these things that just kind of fell off, haha. Hopefully everything will start to get closed now. If you do have any new or additional comments, always feel free to open an issue!

**Comment by cyberwombat** [comment]
I noticed the docs don't mention using the named error constructors directly (i.e. new NotFound()). Is there a reason why? also since they are factories it seems that `throw NotFound` would be the call but ESLint balks at the capitalization. Is the future going to using these as legit constructors or heading towards a camelCase factory var?

**Comment by dougwilson** [comment]
The docs for using the constructor is here: https://github.com/jshttp/http-errors/blob/master/README.md#new-createerrorcode--namemsg

**Comment by dougwilson** [comment]
Please open a new issue if you're having issues or need help instead of a 2 year closed issue.
