### ISSUE TITLE
error expose undefined?

### ISSUE THREAD

**Issue by raistlinthewiz** [jshttp/http-errors#31]
creating error like this;

`return next(createError(500, 'Likit yere döküldü :/',  { expose: false }));`

but getting an undefined when i try to print it.

`		console.dir(err.expose);`

**Comment by dougwilson** [comment]
Hi @raistlinthewiz, I'm really sorry, but there is probably something wrong with your code. Most likely, the `console.dir(err.expose)` you are seeing has `err` not created from your first statement (it's impossible for me to tell, since you only provided two very independency code snippets.

If you want to test this out using this module directly, without the influence of any other code or modules, you can do this on the command line as follows:
```
$ npm i http-errors
http-errors@1.4.0 node_modules\http-errors
├── statuses@1.2.1
└── inherits@2.0.1

$ node -e 'createError=require("http-errors");err=createError(500,"Likit yere döküldü :/",{expose:false});console.dir(err.expose);'
false
```
