### ISSUE TITLE
When do I use new createError vs just createError

### ISSUE THREAD

**Issue by MagnumDopus** [jshttp/http-errors#34]
I am not the brightest bulb in the box.  I understand that when you create a new instance of an object it returns the prototype of that object.  However doing Object.getPrototypeOf on both createError and new createError seem to both return the error proto.  It seems like the former makes more sense since it allows for more options to be specified.  

Is there any real reason to use one over the other?  I will be throwing these inside a promise chain on an express server to handle error reporting to the client.

**Comment by dougwilson** [comment]
So the funny thing in JavaScript is that you can use `new` on any function. The `createError` is just a plain function and using `new` on it (i.e. `new createError()`) does not cause a different result from just `createError()`. This is because all the `new` keyword does is create a `this` context in the function you call with a new object instance. If that function has a `return` and / or does not even use `this` in the body, then the `new` keyword is not going to change the behavior.

**Comment by MagnumDopus** [comment]
So just to clarify, in the case of using createError for error throwing in a promise chain, the term "new" is pretty much optional, or that is to say, I don't get any benefit from using it?

**Comment by dougwilson** [comment]
Right. So, for example, so we're on the same page :) you should be able to just do the following:
```js
var createError = require('http-errors')

// ... lots of code

throw createError(500, 'oh no!') // or whatever args you want
```

An that would work just find inside promises and you'll get an error object in your promise error handler.

**Comment by MagnumDopus** [comment]
Awesome thanks so much!
