### ISSUE TITLE
how to set response headers?

### ISSUE THREAD

**Issue by araucorp** [jshttp/http-errors#48]
I want to set error response headers when an error occurred. Like Content-Type = application/json. When I passed the {'content-type': 'application/json; charset=utf-8'} as err.headers nothing changed.

```
let err = new Error("{message: 'error'}");
err.status = 405;
err.headers = {"content-type": 'application/json; charset=utf-8'};
err.expose = true;
throw err;
```

Thanks in advance.

**Comment by dougwilson** [comment]
This module is just a collection of error objects. It us up to whatever module that is transforming these errors into a HTTP response to set the headers you stored in the error.

**Comment by G-Rath** [comment]
@dougwilson just to confirm that I'm understanding you correctly, you're saying that `createError` by itself *shouldn't* result in the error being sent, and that we still have to send it using `res` in `express`?

I'm currently working off a project setup using your `express-generator`, which has at the end of `app.js`:

```
// catch 404 and forward to error handler
app.use((req, res, next) => next(createError(HttpStatus.NOT_FOUND)));

// error handler
app.use((err: any, req: express.Request, res: express.Response) => {
    console.log('got to this point');
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    if (req.app.get('env') === 'development' && err.status !== HttpStatus.NOT_FOUND) {
        console.log(err);
    }

    // render the error page
    res.status(err.status || HttpStatus.INTERNAL_SERVER_ERROR);
    res.end();
});
```

(This project is in `typescript`, and `HttpStatus` is just a library that exports all Http codes as constants).

I'm trying to get it to send `json`, which in theory (as I understand it) should just be a simple matter of replacing `res.end()` with `res.json()`, but for some reason it's not getting to the error handling middleware.

It seems to be sending immediately when I call `createError`. It this the expected behaviour? (I suspect it could be related to `next()`, but don't know for sure).
