### ISSUE TITLE
import createError from 'http-errors' throws error and stops JS scenario in IE11

### ISSUE THREAD

**Issue by ostapgv** [jshttp/http-errors#52]
If you use `import createError from 'http-errors'` (v1.7.0) and compile sources using babel you'll get an error in IE11. It works fine in the previous 1.6.3 version. 

![screen shot 2018-08-07 at 12 09 31](https://user-images.githubusercontent.com/13677756/43841830-55ab46e6-9b24-11e8-9715-b350931230ae.png)

![screen shot 2018-08-07 at 12 09 52](https://user-images.githubusercontent.com/13677756/43841842-595947f2-9b24-11e8-94a8-3b962ae7d0fa.png)

**Comment by dougwilson** [comment]
This module only works in Node.js, not in IE11. See https://github.com/jshttp/http-errors#install

If you're interested in making it work in a web browser, please open a pull request with the necessary changes and tests that will test this module in the needed web browsers so we can actually keep it running as we make changes 👍 Then we can document the browser support in the README.

**Comment by agataLu** [comment]
This error also occurs in my case, as far as I was able to investigate the problem is with getOwnPropertyDescriptor returning undefined in some scenarios (eg. wrong order of included scripts etc. ). Even if this module was designed to be used with Node, the fix is really simple and I consider it even a good practice (just ensure desc exist), so maybe it will be a low cost to introduce it?
desc.configurable -> desc && desc.configurable

https://github.com/jshttp/http-errors/pull/53
