### ISSUE TITLE
How to use error constructors directly

### ISSUE THREAD

**Issue by cyberwombat** [jshttp/http-errors#55]
I noticed the docs don't mention using the named error constructors directly (i.e. new NotFound()). Is there a reason why? also since they are factories it seems that throw NotFound would be the call but ESLint balks at the capitalization. Is the future going to using these as legit constructors or heading towards a camelCase factory var?

The [docs](https://github.com/jshttp/http-errors/blob/master/README.md#new-createerrorcode--namemsg) do **not** mention using the named constructor directly though the code exports them.

**Comment by dougwilson** [comment]
Thanks for the report. I'm afraid I really don't understand what you're describing the issue as. Is this an issue in the code or just a docs issue? Would you be willing to make a pull request either way with what you're looking for?

**Comment by cyberwombat** [comment]
Id be happy to amend the docs but I need clarification on usage. The exported functions as discussed in another [issue](https://github.com/jshttp/http-errors/issues/11) are factory created rather than actual extensions of the Error object. Therefore both of these work:
````
throw new NotFound(); // Redundant and causes two objects to be created as mentioned in [issue](https://github.com/jshttp/http-errors/issues/11)
throw NotFound() // More "correct" but ESLint balks at naming convention of non constructor.
````
While both of these methods work they are not mentioned directly in the docs as far as I can read it.

So if the constructor approach is to eventually be implemented then the docs should mention this and an issue opened perhaps to return a true constructor.

If the second method is to be used then perhaps camelCasing the factory vars would be the next task?

**Comment by dougwilson** [comment]
I still don't really seem to understand what you mean.

If they are not a true constructor, then I'm really at a loss there. What needs to change in the code to make those exports a true constructor?

And I'm confused on the whole camelCase thing you're talking about as well.

I'm not sure if maybe I'm just tired or what as to why I'm just not connecting with you on what you mean or something else. Perhaps a pull request of some kind may explain better?

**Comment by cyberwombat** [comment]
By redundant constructor I am referring to this [comment](https://github.com/jshttp/http-errors/issues/11#issuecomment-60852301). The code creates an instance of an Error object then modifies it - which returns a ready to go error object that doesn't need another new. 

By the camelCase I am referring to ESlint naming convention that says to use camelCase and only use BumpyCase  for real constructors. Therefore requiring the redundant `new` keyword.

Its not a big deal - I was merely asking because Ive been using this lib for a while and have never really known how to use it. I end up creating a file that exports the camelCase version of the error just to avoid ESLint errors because I was unclear as to whether I should use the `new` keyword since it was not needed. So that got me reading the issues to see where things were going :)

**Comment by dougwilson** [comment]
Ok, I think it's a combination of tired and trying to respond while busy at work :) I went back and re-read the entire issue you linked to and I believe I am understanding what your saying:

The "constructors" that this module exports like `NotFound` actually create a new `Error` object within them and return that, effectively acting like a factory (i.e. if you use the `new` keyword, the created object instance is simply discarded). The idea when those objects were added was to make them to constructors, but it turns out JavaScript makes it really hard to actually subclass `Error` property, as hinted on in the top of the linked issue, so it just instead manipulates a new `Error` object.

I believe the idea is that they _should_ be constructors when it becomes possible one day, and since the constructed `Error` object actually ends up inheriting from the "constructor" it would seem weird if they were camelCase instead of PascalCase since you can do `var e = NotFound(); console.dir(e instanceof NotFound)` and it works just fine (I wonder if your ESLint settings would end up warning about `e instanceof notFound`?).

The "constructors" themselves do work with and without the `new` keyword, just like the built-in `Error` object does (i.e. you can `throw new Error()` and `throw Error()`), but yes, the exports from this module are a factory as an impementation detail, though from the outside they act like constructors (you can `instanceof` against them, etc.).

I don't think any of this was a direct answer to your question, but I have to got to a meeting, so will circle back on this in a bit.

**Comment by cyberwombat** [comment]
Thanks. That actually was the answer - "should be constructors when it becomes possible one day". It makes clearer as to the desired usage and I will make a PR for docs to clarify that these can indeed be used directly instead of only through `createError.xxx`.

**Comment by dougwilson** [comment]
Well, you can always assign properties to your own variables. The docs just show it off `createError` because that's what we named the export at the top of the file in `var createError = require('http-errors')` (thus it would be `createError.NotFound` since the module was imported as `createError`; it's standard JavaScript to also do `var NotFound = createError.NotFound; new NotFound()`, right?).

**Comment by cyberwombat** [comment]
Huh yes. But you export NotFound directly too which is the part of the docs that seems to be missing yes?

**Comment by dougwilson** [comment]
So this is a CJS module, and a CJS module only has one export, which in this case it is the createError function. To export more things like this functions they are added on as properties to that single CJS export.

**Comment by cyberwombat** [comment]
You mean default export?
```
const { NotFound } = require('http-errors')
throw new NotFound()
```

**Comment by dougwilson** [comment]
So you're showing es6 deconstruction. It's just pulling the property with the same name from the export. It's just es6 sugar of the following es5:

```js
var createError = require('http-errors')
var NotFound = createError.NotFound
throw new NotFound()
```

**Comment by cyberwombat** [comment]
I'm not sure I follow. You are [calling](https://github.com/jshttp/http-errors/blob/master/index.js#L258) exports on every http error. So sure, deconstructing the main module but not sure I understand how that affects me calling:
```
throw new NotFound()
```

**Comment by dougwilson** [comment]
I'm not following.
