### ISSUE TITLE
A low-level question

### ISSUE THREAD

**Issue by sdw-123-sdw** [jshttp/http-errors#94]
When I use next (createError (500)) to create an httpError, and the error is returned to the client, will the remaining code on the server be stopped? Or will it return to the next place and continue to execute downward?

**Comment by codinginflow** [comment]
That depends on how you handle the error on the backend. If you don't catch it, your server will go down (like any other error). If you catch it, you can proceed however you want (probably return the error response to the client and return).

**Comment by jaydenseric** [comment]
It's impossible to answer the question raised by this issue, because it doesn't specify what library or framework is using these errors created by `http-errors`. If you were to specify the framework in the question, then it becomes a usage question about that particular framework that should be asked of their community and it isn’t a relevant question for this repo.
